version: "3.8"

services:
    laravel-app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            - APP_ENV=${APP_ENV:-production}
            - APP_DEBUG=${APP_DEBUG:-false}
            - APP_KEY=${APP_KEY}
            - DB_CONNECTION=${DB_CONNECTION:-pgsql}
            - DB_HOST=${DB_HOST:-postgres}
            - DB_PORT=${DB_PORT:-5432}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        depends_on:
            - postgres
            - redis
        volumes:
            - ./:/var/www
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/nginx.conf
            - /etc/letsencrypt/live/testiranje.de/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
            - /etc/letsencrypt/live/testiranje.de/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
        depends_on:
            - laravel-app
        networks:
            - app-network

    postgres:
        image: postgres:13
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app-network

    redis:
        image: redis:alpine
        restart: unless-stopped
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    postgres_data:
